<a href="https://colab.research.google.com/github/Cheetah-lhp/MachineLearning/blob/main/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import numpy as np
from tensorflow.keras.datasets import mnist

In [85]:
data = mnist.load_data()

In [86]:
x_train, y_train = data[0]
x_test, y_test = data[1]

In [87]:
print(x_train.shape, y_train.shape)

(60000, 28, 28) (60000,)


In [88]:
x_train = x_train.reshape(-1, 28*28) / 255.0
x_test = x_test.reshape(-1, 28*28) / 255.0

In [89]:
def one_hot(y):
  y_onehot = np.zeros((len(y), 10))
  for i in range(len(y)):
    y_onehot[i, y[i]] = 1
  return y_onehot

In [90]:
y_train = one_hot(y_train)
y_test = one_hot(y_test)

In [91]:
print(y_train[0:10])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [92]:
input_size = 784
hidden_size = 30
output_size = 10

w1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size,1))

w2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size,1))

lr = 0.5
epochs = 5

In [93]:
def sigmoid(z):
  return 1 / (1+np.exp(-z))

In [96]:
for epoch in range(epochs):
  for i in range(len(x_train)):
    loss = 0
    x = x_train[i].reshape(784,1)
    y = y_train[i].reshape(10,1)

    z1 = np.dot(w1, x) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(w2, a1) + b2
    a2 = sigmoid(z2)

    delta2 = (a2 - y) * a2 * (1 - a2)
    dw2 = np.dot(delta2, a1.T)
    db2 = delta2

    delta1 = np.dot(w2.T, delta2) * a1 * (1 - a1)
    dw1 = np.dot(delta1, x.T)
    db1 = delta1

    w1 -= lr * dw1
    b1 -= lr * db1
    w2 -= lr * dw2
    b2 -= lr * db2
    loss += np.mean(np.square(a2 - y)) #MSE
  print(f"Epoch: {epoch} Loss: {loss}")

Epoch: 0 Loss: 0.000775185680321773
Epoch: 1 Loss: 0.00022090944609227118
Epoch: 2 Loss: 9.204086242946461e-05
Epoch: 3 Loss: 2.135478841198426e-05
Epoch: 4 Loss: 6.20045483162459e-05


In [97]:
correct = 0

for i in range(len(x_test)):
  x = x_test[i].reshape(784,1)

  z1 = np.dot(w1, x) + b1
  a1 = sigmoid(z1)

  z2 = np.dot(w2, a1) + b2
  a2 = sigmoid(z2)

  pred = np.argmax(a2)

  if pred == np.argmax(y_test[i]):
    correct += 1
print("Acc: ", correct / len(x_test))

Acc:  0.9432
